//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMaster.Storage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskMasterSQLEntities : DbContext
    {
        public TaskMasterSQLEntities()
            : base("name=TaskMasterSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TaskItemStored> TaskItemStoreds { get; set; }
        public DbSet<PlaySessionStored> PlaySessionStoreds { get; set; }
    }
}
