//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMaster.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItemStored
    {
        public TaskItemStored()
        {
            this.PlaySessions = new HashSet<PlaySessionStored>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<PlaySessionStored> PlaySessions { get; set; }
    }
}
